In [1]:
#read the information of real_estate.csv and load it into a dataframe to preprocess it
import pandas as pd

df = pd.read_csv('Data/real_estate.csv')   # https://www.kaggle.com/datasets/quantbruce/real-estate-price-prediction/
df.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [6]:
#data Preprocessing#  https://www.kaggle.com/code/mehmetutkubala/real-estate-price-prediction
df.rename(columns ={'X2 house age':'house_age'},inplace=True)
df.rename(columns ={'X3 distance to the nearest MRT station':'distance_to_the_nearest_MRT_station'},inplace=True)
df.rename(columns ={'X4 number of convenience stores':'number_of_convenience_stores'},inplace=True)
df.rename(columns ={'X5 latitude':'latitude'},inplace=True)
df.rename(columns ={'X6 longitude':'longitude'},inplace=True)
df.rename(columns ={'Y house price of unit area':'house_price_of_unit_area'},inplace=True)
df.rename(columns ={'X1 transaction date':'transaction_date'},inplace=True)

df["transaction_date"]=df["transaction_date"].astype("int") #We change the type of data in transaction_date to integer.

df.head()

No  transaction_date  house_age  distance_to_the_nearest_MRT_station  \
0   1              2012       32.0                             84.87882   
1   2              2012       19.5                            306.59470   
2   3              2013       13.3                            561.98450   
3   4              2013       13.3                            561.98450   
4   5              2012        5.0                            390.56840   

   number_of_convenience_stores  latitude  longitude  house_price_of_unit_area  
0                            10  24.98298  121.54024                      37.9  
1                             9  24.98034  121.53951                      42.2  
2                             5  24.98746  121.54391                      47.3  
3                             5  24.98746  121.54391                      54.8  
4                             5  24.97937  121.54245                      43.1

In [10]:
x,y=df.drop(["No","house_price_of_unit_area","transaction_date"],axis=1),df[["house_price_of_unit_area"]]

y.head()

house_price_of_unit_area
0                      37.9
1                      42.2
2                      47.3
3                      54.8
4                      43.1

In [25]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x = scaler.fit_transform(x)
y = scaler.fit_transform(y)
# y = y.values.flatten()
print(x)

[[0.73059361 0.00951267 1.         0.61694135 0.71932284]
 [0.44520548 0.04380939 0.9        0.5849491  0.71145137]
 [0.30365297 0.08331505 0.5        0.67123122 0.75889584]
 ...
 [0.42922374 0.05686115 0.7        0.57149782 0.71522536]
 [0.18493151 0.0125958  0.5        0.42014057 0.72395946]
 [0.14840183 0.0103754  0.9        0.51211827 0.75016174]]


In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state= 42)

In [22]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)



(331, 5)
(83, 5)
(331, 1)
(83, 1)


In [16]:
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(50, activation="relu"),
    tf.keras.layers.Dense(25, activation="relu"),
    tf.keras.layers.Dense(1),
])

sgd = tf.keras.optimizers.SGD(lr = 0.01, momentum = 0.9)
model.compile(optimizer=sgd, loss = "mse", metrics=["mae"])
model.fit(x_train, y_train, epochs=100, verbose="2")

Epoch 1/100
Epoch 2/100
Epoch 3/100
Epoch 4/100
Epoch 5/100
Epoch 6/100
Epoch 7/100
Epoch 8/100
Epoch 9/100
Epoch 10/100
Epoch 11/100
Epoch 12/100
Epoch 13/100
Epoch 14/100
Epoch 15/100
Epoch 16/100
Epoch 17/100
Epoch 18/100
Epoch 19/100
Epoch 20/100
Epoch 21/100
Epoch 22/100
Epoch 23/100
Epoch 24/100
Epoch 25/100
Epoch 26/100
Epoch 27/100
Epoch 28/100
Epoch 29/100
Epoch 30/100
Epoch 31/100
Epoch 32/100
Epoch 33/100
Epoch 34/100
Epoch 35/100
Epoch 36/100
Epoch 37/100
Epoch 38/100
Epoch 39/100
Epoch 40/100
Epoch 41/100
Epoch 42/100
Epoch 43/100
Epoch 44/100
Epoch 45/100
Epoch 46/100
Epoch 47/100
Epoch 48/100
Epoch 49/100
Epoch 50/100
Epoch 51/100
Epoch 52/100
Epoch 53/100
Epoch 54/100
Epoch 55/100
Epoch 56/100
Epoch 57/100
Epoch 58/100
Epoch 59/100
Epoch 60/100
Epoch 61/100
Epoch 62/100
Epoch 63/100
Epoch 64/100
Epoch 65/100
Epoch 66/100
Epoch 67/100
Epoch 68/100
Epoch 69/100
Epoch 70/100
Epoch 71/100
Epoch 72/100
Epoch 73/100
Epoch 74/100
Epoch 75/100
Epoch 76/100
Epoch 77/100
Epoch 78

In [29]:
# predict the test values
x_pred_test = model.predict(x_test)
y_pred_train = model.predict(x_train)

11/11 [==============================] - 0s 3ms/step
