In [2]:
import MyNeuralNetwork as NeuralNetwork
import activation_functions as activation

# initiaize neural network

# layers include input layer + hidden layers + output layer
layers = [4,9,5,1]
nn = NeuralNetwork.MyNeuralNetwork(layers,  1, 0.01, 0.9, activation.linear, 0.2)
nn.initialize_weights()
print("matrices of weights with random values")
print(nn.w)

nn.initialize_weights_for_test()
# matrices are initialized to ones for testing the implementation of neural network 
print("matrices of weights ")
print(nn.w)

print("matrix of weights between input layer and first hidden layer")
print(nn.w[1])

print("weights between input layer and first neuron in first hidden layer")
print(nn.w[1][0])

print("the weight between unit 3 in input layer and unit 0 in first hidden layer")
print(nn.w[1][0,3])

print("each matrix of weights in a new line")
for item in nn.w:
    print(item)

matrices of weights with random values
[array([[0.39402298]]), array([[0.68822065, 0.95698789, 0.03407494, 0.29222751],
       [0.21953864, 0.85606515, 0.84286063, 0.02366022],
       [0.30891708, 0.48772578, 0.75061832, 0.48033336],
       [0.78131407, 0.2383594 , 0.28668023, 0.37520793],
       [0.79614279, 0.69312432, 0.73924907, 0.55845361],
       [0.82351927, 0.26864156, 0.84560607, 0.63895156],
       [0.48246527, 0.46022828, 0.64577108, 0.98376799],
       [0.49852105, 0.01069646, 0.65490498, 0.27022212],
       [0.6733082 , 0.45661774, 0.06662126, 0.17964892]]), array([[0.81136553, 0.65904482, 0.58862   , 0.07545231, 0.98965776,
        0.19984949, 0.14963992, 0.30491485, 0.25448954],
       [0.86165667, 0.39978686, 0.90713851, 0.31936024, 0.82250001,
        0.15128992, 0.96313013, 0.62027553, 0.64992854],
       [0.12319685, 0.71613281, 0.78509192, 0.35210099, 0.82188898,
        0.46260566, 0.02213105, 0.0767303 , 0.67126182],
       [0.31241633, 0.58951222, 0.01758005, 0.5

In [3]:
# testing feedforward

import numpy as np

input = [1,1,1,1] 
o = nn.feedforward(np.array(input))

print(o)

print(nn.h)

print(nn.xi)

[180.]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]


In [4]:
# testing backpropagate
z = 150 
o = 180
nn.backpropagate(o, z)
print(nn.delta)


[array([0., 0., 0., 0.]), array([150., 150., 150., 150., 150., 150., 150., 150., 150.]), array([30., 30., 30., 30., 30.]), array([30.])]


In [5]:
# testing update weights
nn.eta = -1
nn.alpha = 0

# print(nn.d_w_prev)
# print(nn.d_theta_prev)

print(nn.delta)
print(nn.xi)

# print(nn.delta[1])
# print(nn.xi[0])

print(np.outer(nn.delta[1], nn.xi[0]))

nn.update_weights()

print(nn.w)




[array([0., 0., 0., 0.]), array([150., 150., 150., 150., 150., 150., 150., 150., 150.]), array([30., 30., 30., 30., 30.]), array([30.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[[150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]]
[array([[1.]]), array([[151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.]]), array([[121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121

In [6]:
# testing matrix operations
import numpy as np
a = [1,2,3] 
b = [4,5,6]

# c = a * b
# print(c)

d = np.array(a) * np.array(b)
print(d)

e = np.dot(a,b)
print(e)

f = np.dot(np.array(a), np.array(b))
print(f)

g = [[1,2,3] , [4,5,6]]
print(g)

h = [[7,8,9] , [10,11,12] ]
print(h)

i = np.array(g) * np.array(h)
print(i)

# j = np.dot(g, h)
# print(j)

k = np.outer(np.array(g), np.array(h))
print(k)

print(np.array(g))

print(np.random.random((3, 4)))



[ 4 10 18]
32
32
[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]
[[ 7 16 27]
 [40 55 72]]
[[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]
[[1 2 3]
 [4 5 6]]
[[0.82848628 0.34424859 0.79800944 0.69413527]
 [0.96340643 0.91089592 0.79662444 0.71045546]
 [0.83395341 0.3853429  0.69766325 0.58636388]]


In [7]:
#random weights

nn = NeuralNetwork.MyNeuralNetwork(layers,  1, 0.01, 0.9, activation.linear, 0.2)
nn.initialize_weights()
print(nn.w)



[array([[0.8722041]]), array([[0.01821479, 0.65269217, 0.33960138, 0.64607468],
       [0.43902211, 0.16826261, 0.83530906, 0.30378434],
       [0.21507333, 0.33662178, 0.71079248, 0.18084826],
       [0.77385482, 0.17192225, 0.62697588, 0.63676965],
       [0.86307598, 0.74618447, 0.3269116 , 0.71362697],
       [0.91482211, 0.63532283, 0.1135989 , 0.47924953],
       [0.96499987, 0.79362173, 0.23192668, 0.26733757],
       [0.64292694, 0.59763073, 0.74017279, 0.17842181],
       [0.46318299, 0.14638359, 0.2604946 , 0.43824437]]), array([[0.51921836, 0.95131822, 0.30465384, 0.27034125, 0.20503333,
        0.00467456, 0.4345397 , 0.12778531, 0.97572699],
       [0.23435806, 0.2690138 , 0.27831359, 0.95300453, 0.74202943,
        0.63501941, 0.22947763, 0.23539384, 0.94932669],
       [0.28498883, 0.27772116, 0.20051512, 0.6430314 , 0.27758333,
        0.79436257, 0.51746816, 0.69652181, 0.54499599],
       [0.57584082, 0.57831687, 0.27840622, 0.32913959, 0.71637885,
        0.77272025,