In [3]:
import MyNeuralNetwork as NeuralNetwork
import activation_functions as activation

# initiaize neural network

# layers include input layer + hidden layers + output layer
layers = [4,9,5,1]
nn = NeuralNetwork.MyNeuralNetwork(layers,  1, 0.01, 0.9, activation.linear, 0.2)
nn.initialize_weights()
print("matrices of weights with random values")
print(nn.w)

nn.initialize_weights_for_test()
# matrices are initialized to ones for testing the implementation of neural network 
print("matrices of weights ")
print(nn.w)

print("matrix of weights between input layer and first hidden layer")
print(nn.w[1])

print("weights between input layer and first neuron in first hidden layer")
print(nn.w[1][0])

print("the weight between unit 3 in input layer and unit 0 in first hidden layer")
print(nn.w[1][0,3])

print("each matrix of weights in a new line")
for item in nn.w:
    print(item)

matrices of weights with random values
[array([[0.58934215]]), array([[0.54983348, 0.97128304, 0.24013131, 0.82046452],
       [0.33839943, 0.85339566, 0.46579217, 0.64533012],
       [0.25991222, 0.53513653, 0.57903396, 0.95000085],
       [0.55836317, 0.27754924, 0.3938204 , 0.12336952],
       [0.8617237 , 0.6252125 , 0.24719642, 0.37975567],
       [0.72719865, 0.32567929, 0.71973184, 0.05816404],
       [0.5358124 , 0.79720838, 0.94997229, 0.96787674],
       [0.3192139 , 0.83829911, 0.67362837, 0.07786306],
       [0.63768137, 0.64816092, 0.91793076, 0.7423953 ]]), array([[0.32507885, 0.70550956, 0.76823849, 0.22131457, 0.68713609,
        0.3984832 , 0.90246547, 0.10491402, 0.23523483],
       [0.07652327, 0.11409267, 0.54900444, 0.08488514, 0.08745527,
        0.15241817, 0.08792714, 0.79296101, 0.25147831],
       [0.29913784, 0.98458313, 0.12937695, 0.45306413, 0.6120746 ,
        0.55990211, 0.39876436, 0.12389714, 0.71927764],
       [0.20689158, 0.09964339, 0.27678872, 0.5

In [4]:
# testing feedforward

import numpy as np

input = [1,1,1,1] 
o = nn.feedforward(np.array(input))

print(o)

print(nn.h)

print(nn.xi)

[180.]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]


In [5]:
# testing backpropagate
z = 150 
o = 180
nn.backpropagate(o, z)
print(nn.delta)


[array([0., 0., 0., 0.]), array([150., 150., 150., 150., 150., 150., 150., 150., 150.]), array([30., 30., 30., 30., 30.]), array([30.])]


In [6]:
# testing update weights
nn.eta = -1
nn.alpha = 0

# print(nn.d_w_prev)
# print(nn.d_theta_prev)

print(nn.delta)
print(nn.xi)

# print(nn.delta[1])
# print(nn.xi[0])

print(np.outer(nn.delta[1], nn.xi[0]))

nn.update_weights()

print(nn.w)




[array([0., 0., 0., 0.]), array([150., 150., 150., 150., 150., 150., 150., 150., 150.]), array([30., 30., 30., 30., 30.]), array([30.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[[150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]]
[array([[1.]]), array([[151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.]]), array([[121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121

In [7]:
# testing matrix operations
import numpy as np
a = [1,2,3] 
b = [4,5,6]

# c = a * b
# print(c)

d = np.array(a) * np.array(b)
print(d)

e = np.dot(a,b)
print(e)

f = np.dot(np.array(a), np.array(b))
print(f)

g = [[1,2,3] , [4,5,6]]
print(g)

h = [[7,8,9] , [10,11,12] ]
print(h)

i = np.array(g) * np.array(h)
print(i)

# j = np.dot(g, h)
# print(j)

k = np.outer(np.array(g), np.array(h))
print(k)

print(np.array(g))

print(np.random.random((3, 4)))



[ 4 10 18]
32
32
[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]
[[ 7 16 27]
 [40 55 72]]
[[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]
[[1 2 3]
 [4 5 6]]
[[0.77137665 0.02137756 0.12551376 0.03900258]
 [0.36411522 0.09827614 0.56755283 0.36764027]
 [0.76078408 0.85985694 0.23500355 0.45698161]]


In [8]:
#random weights

nn = NeuralNetwork.MyNeuralNetwork(layers,  1, 0.01, 0.9, activation.linear, 0.2)
nn.initialize_weights()
print(nn.w)


[array([[0.08356488]]), array([[0.27158261, 0.24138491, 0.34508399, 0.56770411],
       [0.47883523, 0.37056131, 0.13661269, 0.65542738],
       [0.243915  , 0.94271404, 0.85736218, 0.75298847],
       [0.12638259, 0.50121276, 0.90521385, 0.90087711],
       [0.24551316, 0.58259801, 0.06830017, 0.26279189],
       [0.74853776, 0.37670713, 0.67709069, 0.96219502],
       [0.76460263, 0.64464601, 0.31925483, 0.62002453],
       [0.70649962, 0.34356586, 0.91442429, 0.56475624],
       [0.23827981, 0.64934151, 0.45456101, 0.59913825]]), array([[5.92124654e-01, 8.13947046e-01, 6.72881037e-01, 1.28493049e-03,
        5.98677044e-01, 2.18910557e-01, 6.59409148e-01, 9.75368052e-01,
        1.62631516e-01],
       [8.89498387e-01, 3.60480436e-01, 4.06910626e-01, 8.73703213e-02,
        4.24754518e-02, 6.97427840e-01, 9.38327993e-01, 2.78378579e-01,
        1.83136284e-02],
       [8.38826353e-01, 2.49113138e-01, 3.64471844e-01, 6.75589390e-01,
        7.14583967e-01, 7.60183386e-01, 8.98575072e