In [16]:
import MyNeuralNetwork as NeuralNetwork
import activation_functions as activation

# initiaize neural network

# layers include input layer + hidden layers + output layer
layers = [4,9,5,1]
nn = NeuralNetwork.MyNeuralNetwork(layers,  1, 0.01, 0.9, activation.linear, 0.2)
nn.initialize_weights()
print("matrices of weights with random values")
print(nn.w)

nn.initialize_weights_for_test()
# matrices are initialized to ones for testing the BP implementation of neural network 
print("matrices of weights ")
print(nn.w)

print("matrix of weights between input layer and first hidden layer")
print(nn.w[1])

print("weights between input layer and first neuron in first hidden layer")
print(nn.w[1][0])

print("the weight between unit 3 in input layer and unit 0 in first hidden layer")
print(nn.w[1][0,3])

print("each matrix of weights in a new line")
for item in nn.w:
    print(item)

matrices of weights with random values
[array([[0.50152525]]), array([[0.81871425, 0.8715117 , 0.96494655, 0.20479833],
       [0.35552204, 0.91635349, 0.17616507, 0.90153204],
       [0.9147812 , 0.39611932, 0.51493443, 0.49636553],
       [0.7526923 , 0.47667156, 0.17591448, 0.92757758],
       [0.91223916, 0.19405441, 0.42991691, 0.15990381],
       [0.50180471, 0.05304676, 0.61685568, 0.76138127],
       [0.83517682, 0.12271492, 0.55412232, 0.08660055],
       [0.38352343, 0.74012736, 0.43348879, 0.77590567],
       [0.83437953, 0.24524865, 0.97335625, 0.01437532]]), array([[0.30957727, 0.82018877, 0.31656457, 0.21634555, 0.6531189 ,
        0.50593969, 0.78926121, 0.609888  , 0.08074946],
       [0.12150394, 0.96370798, 0.45818689, 0.70960697, 0.41699574,
        0.67063073, 0.77226864, 0.34949508, 0.84621954],
       [0.24437089, 0.56466056, 0.0569883 , 0.76664953, 0.38918448,
        0.50948579, 0.88640669, 0.33886575, 0.60317968],
       [0.75829548, 0.15879394, 0.12069662, 0.2

In [17]:
# testing feedforward

import numpy as np

input = [1,1,1,1] 
o = nn.feedforward(np.array(input))

print(o)

print(nn.h)

print(nn.xi)

[180.]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]


In [19]:
# testing backpropagate
print(nn.h)
print(nn.w)
z = 150 
o = 180
nn.backpropagate(o, z)
print(nn.delta)


[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[array([[1.]]), array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]]), array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]]), array([[1., 1., 1., 1., 1.]])]
[array([0., 0., 0., 0.]), array([150., 150., 150., 150., 150., 150., 150., 150., 150.]), array([30., 30., 30., 30., 30.]), array([30.])]


In [12]:
# testing update weights
nn.eta = -1
nn.alpha = 0

# print(nn.d_w_prev)
# print(nn.d_theta_prev)

print(nn.delta)
print(nn.xi)

# print(nn.delta[1])
# print(nn.xi[0])

print(np.outer(nn.delta[1], nn.xi[0]))

nn.update_weights()

print(nn.w)




[array([0., 0., 0., 0.]), array([150., 150., 150., 150., 150., 150., 150., 150., 150.]), array([30., 30., 30., 30., 30.]), array([30.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[[150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]]
[array([[1.]]), array([[151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.]]), array([[121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121

In [13]:
# testing matrix operations
import numpy as np
a = [1,2,3] 
b = [4,5,6]

# c = a * b
# print(c)

d = np.array(a) * np.array(b)
print(d)

e = np.dot(a,b)
print(e)

f = np.dot(np.array(a), np.array(b))
print(f)

g = [[1,2,3] , [4,5,6]]
print(g)

h = [[7,8,9] , [10,11,12] ]
print(h)

i = np.array(g) * np.array(h)
print(i)

# j = np.dot(g, h)
# print(j)

k = np.outer(np.array(g), np.array(h))
print(k)

print(np.array(g))

print(np.random.random((3, 4)))



[ 4 10 18]
32
32
[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]
[[ 7 16 27]
 [40 55 72]]
[[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]
[[1 2 3]
 [4 5 6]]
[[0.39878021 0.45630808 0.09284275 0.6123864 ]
 [0.25343111 0.98661152 0.92175714 0.87143413]
 [0.9444051  0.4178791  0.5176061  0.62488104]]


In [14]:
#random weights

nn = NeuralNetwork.MyNeuralNetwork(layers,  1, 0.01, 0.9, activation.linear, 0.2)
nn.initialize_weights()
print(nn.w)



[array([[0.80053365]]), array([[0.38082102, 0.80646714, 0.28011449, 0.20954672],
       [0.51026099, 0.67766125, 0.77505771, 0.19341928],
       [0.49555899, 0.62105568, 0.26004972, 0.36723419],
       [0.38269062, 0.38670775, 0.31771072, 0.15802731],
       [0.06820879, 0.03773428, 0.72401191, 0.06487724],
       [0.49282259, 0.17899633, 0.75471828, 0.28315142],
       [0.87305032, 0.73539097, 0.73912679, 0.93288824],
       [0.6031046 , 0.65680859, 0.81229627, 0.17218296],
       [0.86984118, 0.04635437, 0.5433734 , 0.55359295]]), array([[0.50132759, 0.76884137, 0.11371394, 0.03558936, 0.39770582,
        0.33917462, 0.64570701, 0.73887063, 0.50254738],
       [0.14010943, 0.33553267, 0.35733196, 0.85649699, 0.76762628,
        0.1393163 , 0.93855955, 0.33931542, 0.61171203],
       [0.78080425, 0.04696913, 0.17726882, 0.85553582, 0.57838229,
        0.53174956, 0.79372174, 0.70817942, 0.69462584],
       [0.56929594, 0.99015863, 0.44094644, 0.19535415, 0.49976824,
        0.58256861