In [6]:
import MyNeuralNetwork as NeuralNetwork
import activation_functions as activation

# initiaize neural network

# layers include input layer + hidden layers + output layer
layers = [4,9,5,1]
nn = NeuralNetwork.MyNeuralNetwork(layers,  1, 0.01, 0.9, activation.linear, 0.2)
nn.initialize_weights_for_test()
# matrices are initialized to ones for testing the implementation of neural network 
print("matrices of weights")
print(nn.w)

print("matrix of weights between input layer and first hidden layer")
print(nn.w[1])

print("weights between input layer and first neuron in first hidden layer")
print(nn.w[1][0])

print("the weight between unit 3 in input layer and unit 0 in first hidden layer")
print(nn.w[1][0,3])

print("each matrix of weights in a new line")
for item in nn.w:
    print(item)

matrices of weights
[array([[1.]]), array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]]), array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]]), array([[1., 1., 1., 1., 1.]])]
matrix of weights between input layer and first hidden layer
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
weights between input layer and first neuron in first hidden layer
[1. 1. 1. 1.]
the weight between unit 3 in input layer and unit 0 in first hidden layer
1.0
each matrix of weights in a new line
[[1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1.

In [7]:
# testing feedforward

import numpy as np

input = [1,1,1,1] 
o = nn.feedforward(np.array(input))

print(o)

print(nn.h)

print(nn.xi)

[180.]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]


In [8]:
# testing backpropagate
z = 150 
o = 180
nn.backpropagate(o, z)
print(nn.delta)


[array([0., 0., 0., 0.]), array([150., 150., 150., 150., 150., 150., 150., 150., 150.]), array([30., 30., 30., 30., 30.]), array([30.])]


In [9]:
# testing update weights
nn.eta = -1
nn.alpha = 0

# print(nn.d_w_prev)
# print(nn.d_theta_prev)

print(nn.delta)
print(nn.xi)

# print(nn.delta[1])
# print(nn.xi[0])

print(np.outer(nn.delta[1], nn.xi[0]))

nn.update_weights()

print(nn.w)




[array([0., 0., 0., 0.]), array([150., 150., 150., 150., 150., 150., 150., 150., 150.]), array([30., 30., 30., 30., 30.]), array([30.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[[150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]]
[array([[1.]]), array([[151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.],
       [151., 151., 151., 151.]]), array([[121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121

In [10]:
# testing matrix operations
import numpy as np
a = [1,2,3] 
b = [4,5,6]

# c = a * b
# print(c)

d = np.array(a) * np.array(b)
print(d)

e = np.dot(a,b)
print(e)

f = np.dot(np.array(a), np.array(b))
print(f)

g = [[1,2,3] , [4,5,6]]
print(g)

h = [[7,8,9] , [10,11,12] ]
print(h)

i = np.array(g) * np.array(h)
print(i)

# j = np.dot(g, h)
# print(j)

k = np.outer(np.array(g), np.array(h))
print(k)

print(np.array(g))

print(np.random.random((3, 4)))

[ 4 10 18]
32
32
[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]
[[ 7 16 27]
 [40 55 72]]
[[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]
[[1 2 3]
 [4 5 6]]
[[0.02901771 0.85926345 0.38306975 0.32323069]
 [0.41677254 0.0745552  0.71884782 0.66441822]
 [0.1162503  0.0498288  0.10375576 0.46301049]]
