In [1]:
import MyNeuralNetwork as NeuralNetwork
import activation_functions as activation

# initiaize neural network

# layers include input layer + hidden layers + output layer
layers = [4,9,5,1]
nn = NeuralNetwork.MyNeuralNetwork(layers,  1, 0.01, 0.9, activation.linear, 0.2)
nn.initialize_weights()
print("matrices of weights with random values")
print(nn.w)

nn.initialize_weights_for_test()
# matrices are initialized to ones for testing the BP implementation of neural network 
print("matrices of weights ")
print(nn.w)

print("matrix of weights between input layer and first hidden layer")
print(nn.w[1])

print("weights between input layer and first neuron in first hidden layer")
print(nn.w[1][0])

print("the weight between unit 3 in input layer and unit 0 in first hidden layer")
print(nn.w[1][0,3])

print("each matrix of weights in a new line")
for item in nn.w:
    print(item)

matrices of weights with random values
[array([[0.87274881]]), array([[0.19368309, 0.62217871, 0.38376242, 0.66104117],
       [0.19037832, 0.54283306, 0.11733971, 0.76948021],
       [0.40775013, 0.03048987, 0.2936914 , 0.01233108],
       [0.27464207, 0.50802072, 0.84084039, 0.94406492],
       [0.55901674, 0.71928517, 0.90795218, 0.10891071],
       [0.00599477, 0.63776605, 0.48286025, 0.36571692],
       [0.4266913 , 0.6164981 , 0.60576309, 0.11733388],
       [0.5121307 , 0.91899326, 0.18041131, 0.83125867],
       [0.71938841, 0.45775351, 0.75386149, 0.84667754]]), array([[0.1002758 , 0.18539823, 0.43544103, 0.87445907, 0.65840739,
        0.38820793, 0.83032401, 0.31054309, 0.41056804],
       [0.78983813, 0.31567252, 0.22308281, 0.64111904, 0.41911485,
        0.05505352, 0.15339548, 0.62372413, 0.00807312],
       [0.25212719, 0.40158869, 0.42966895, 0.5278202 , 0.4093934 ,
        0.35363132, 0.20099711, 0.7855717 , 0.94863526],
       [0.20357005, 0.92379434, 0.86997503, 0.2

In [2]:
# testing feedforward

import numpy as np

nn.initialize_weights_for_test()
nn.initialize_thresholds_for_test()
input = [1,1,1,1] 
o = nn.feedforward(np.array(input))

print(o)

print(nn.h)

print(nn.xi)

[180.]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]


In [3]:
# testing backpropagate
#print(nn.h)
#print(nn.w[2])
z = 150 
o = 180
nn.backpropagate(o, z)
#print(nn.delta)


In [4]:
#x = np.random.randint(1, 6, size=(2,3))
x = [[1,2,3], [4,5,6]]
x = np.array(x)
print("x = ", x)

y = [[5], [5]]
y = np.array(y)
print("y = ", y)

z = np.dot(y.T,x)
print("z = " , z)

print( z * [1,2,3])

x =  [[1 2 3]
 [4 5 6]]
y =  [[5]
 [5]]
z =  [[25 35 45]]
[[ 25  70 135]]


In [5]:
# testing update weights
nn.eta = -1
nn.alpha = 0

# print(nn.d_w_prev)
# print(nn.d_theta_prev)

print(nn.delta)
print(nn.xi)

print(nn.delta[2].shape)
# print(nn.xi[0])

print(np.outer(nn.delta[1], nn.xi[0]))

nn.update_weights()

print(nn.w)




[array([0., 0., 0., 0.]), array([150., 150., 150., 150., 150., 150., 150., 150., 150.]), array([30., 30., 30., 30., 30.]), array([30.])]
[array([1, 1, 1, 1]), array([4., 4., 4., 4., 4., 4., 4., 4., 4.]), array([36., 36., 36., 36., 36.]), array([180.])]
(5,)
[[150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]]
self.delta[ 1 ] :  [150. 150. 150. 150. 150. 150. 150. 150. 150.]
self.xi[ 0 ] :  [1 1 1 1]
self.d_w[ 1 ] :  [[150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]
 [150. 150. 150. 150.]]
self.delta[ 2 ] :  [30. 30. 30. 30. 30.]
self.xi[ 1 ] :  [4. 4. 4. 4. 4. 4. 4. 4. 4.]
self.d_w[ 2 ] :  [[120. 120. 120. 120. 120. 120. 120. 120. 120.]
 [120. 120. 120. 120. 120. 120. 120. 120. 120.]
 [120. 120. 120. 1

In [6]:
# testing matrix operations
import numpy as np
a = [1,2,3] 
b = [4,5,6]

# c = a * b
# print(c)

d = np.array(a) * np.array(b)
print(d)

e = np.dot(a,b)
print(e)

f = np.dot(np.array(a), np.array(b))
print(f)

g = [[1,2,3] , [4,5,6]]
print(g)

h = [[7,8,9] , [10,11,12] ]
print(h)

i = np.array(g) * np.array(h)
print(i)

# j = np.dot(g, h)
# print(j)

k = np.outer(np.array(g), np.array(h))
print(k)

print(np.array(g))

print(np.random.random((3, 4)))



[ 4 10 18]
32
32
[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]
[[ 7 16 27]
 [40 55 72]]
[[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]
[[1 2 3]
 [4 5 6]]
[[0.87850922 0.49981981 0.01644677 0.05188816]
 [0.43125798 0.1386574  0.09631911 0.61842469]
 [0.12785577 0.12728959 0.33509167 0.55323084]]


In [7]:
#random weights

nn = NeuralNetwork.MyNeuralNetwork(layers,  1, 0.01, 0.9, activation.linear, 0.2)
nn.initialize_weights()
print(nn.w)



[array([[0.13843741]]), array([[0.26355832, 0.4145828 , 0.84737961, 0.27768816],
       [0.79389511, 0.67935676, 0.98583303, 0.5941642 ],
       [0.31841316, 0.14315395, 0.95470862, 0.6824755 ],
       [0.34975182, 0.68047255, 0.92425866, 0.98747408],
       [0.95774327, 0.34225934, 0.3868363 , 0.60958121],
       [0.22147315, 0.21614463, 0.99775689, 0.17650397],
       [0.9380515 , 0.70393679, 0.10269766, 0.62351293],
       [0.66591134, 0.16399399, 0.79844956, 0.96802655],
       [0.54158542, 0.93030965, 0.03700519, 0.96792954]]), array([[0.71587554, 0.7582204 , 0.09871163, 0.73107994, 0.99852831,
        0.10867236, 0.59090591, 0.99478392, 0.04391547],
       [0.63865019, 0.99537852, 0.7007077 , 0.95581861, 0.45512123,
        0.15321425, 0.54658864, 0.95285133, 0.38340271],
       [0.94740962, 0.06081724, 0.39343743, 0.17699634, 0.94675654,
        0.32022314, 0.6461544 , 0.69724055, 0.017381  ],
       [0.12531244, 0.67632341, 0.48755552, 0.89204786, 0.71191087,
        0.07445477